// angular-portfolio-static/src/app/music-work/music-work.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-music-work',
  standalone: true,
  templateUrl: './music-work.component.html',
  styleUrls: ['./music-work.component.css']
})
export class MusicWorkComponent {}

<h1 class="sectionTitle">Music Work</h1>

<div class="musicWork">
  <a href="https://distrokid.com/hyperfollow/neperia/zenaidas-voice" target="_blank" class="musicBox zenaida"></a>
  <a href="https://open.spotify.com/album/0uywQMvMlvIm25Y6AuvIiX?si=W2bMgklWS72_n0PNwzVhSQ" target="_blank" class="musicBox happy"></a>
  <a href="https://open.spotify.com/album/2GKXZGt6iB3yeCb9Kgx819?si=4fM1DOVVSzKToXRRfJXG5w" target="_blank" class="musicBox p13"></a>
  <a href="https://open.spotify.com/album/0CEjQS9olKwHd7zFxoWWCw?si=SiGUv7KiSmekOaXqLTjuFg" target="_blank" class="musicBox vritra"></a>
  <a href="https://open.spotify.com/album/4KwSaACCVsnWI3hhAcDrLd?si=3bqXgAsuSfG0xYOjtvvwXA" target="_blank" class="musicBox minokawa"></a>
  <a href="https://open.spotify.com/album/0YUI0rMbJLVADbVWgRpYLQ?si=LWIlGAveR2C-1vKvOFKsig" target="_blank" class="musicBox scalling"></a>
  <a href="https://open.spotify.com/album/0CChaj3uxMeZc7PVRx79V8?si=4kZMnWGaTa-rBUcCmaBX6Q" target="_blank" class="musicBox runner"></a>
  <a href="https://open.spotify.com/album/4tJWD8sk5Bef99fEW8qqhX?si=5mWHoDlmSlaDRahSFV1juQ" target="_blank" class="musicBox ptesmata"></a>
  <a href="https://open.spotify.com/album/0M7884IhTxOdTZtBK3CsXh?si=R3jgdlTwRXOzz_KlBla8Ug" target="_blank" class="musicBox cybernation"></a>
  <a href="https://open.spotify.com/album/5fviige0btTbQf2hZQ6T8T?si=JkFKXt2fQSSrGSXfsaX0gg" target="_blank" class="musicBox drawing"></a>
</div><br /><br />

// react-portfolio-static/src/components/MusicWork.jsx
import styles from "../styles/all.module.css";

function MusicWork() {
    return (
        <>
            <h1 className={styles.sectionTitle}>Music Work</h1>
            <div className={styles.musicWork}>
                <a href="https://distrokid.com/hyperfollow/neperia/zenaidas-voice" target="_blank"
                    className={`${styles.musicBox} ${styles.zenaida}`}></a>
                <a href="https://open.spotify.com/album/0uywQMvMlvIm25Y6AuvIiX?si=W2bMgklWS72_n0PNwzVhSQ" target="_blank"
                    className={`${styles.musicBox} ${styles.happy}`}></a>
                <a href="https://open.spotify.com/album/2GKXZGt6iB3yeCb9Kgx819?si=4fM1DOVVSzKToXRRfJXG5w" target="_blank"
                    className={`${styles.musicBox} ${styles.p13}`}></a>
                <a href="https://open.spotify.com/album/0CEjQS9olKwHd7zFxoWWCw?si=SiGUv7KiSmekOaXqLTjuFg" target="_blank"
                    className={`${styles.musicBox} ${styles.vritra}`}></a>
                <a href="https://open.spotify.com/album/4KwSaACCVsnWI3hhAcDrLd?si=3bqXgAsuSfG0xYOjtvvwXA" target="_blank"
                    className={`${styles.musicBox} ${styles.minokawa}`}></a>

                <a href="https://open.spotify.com/album/0YUI0rMbJLVADbVWgRpYLQ?si=LWIlGAveR2C-1vKvOFKsig" target="_blank"
                    className={`${styles.musicBox} ${styles.scalling}`}></a>
                <a href="https://open.spotify.com/album/0CChaj3uxMeZc7PVRx79V8?si=4kZMnWGaTa-rBUcCmaBX6Q" target="_blank"
                    className={`${styles.musicBox} ${styles.runner}`}></a>
                <a href="https://open.spotify.com/album/4tJWD8sk5Bef99fEW8qqhX?si=5mWHoDlmSlaDRahSFV1juQ" target="_blank"
                    className={`${styles.musicBox} ${styles.ptesmata}`}></a>
                <a href="https://open.spotify.com/album/0M7884IhTxOdTZtBK3CsXh?si=R3jgdlTwRXOzz_KlBla8Ug" target="_blank"
                    className={`${styles.musicBox} ${styles.cybernation}`}></a>
                <a href="https://open.spotify.com/album/5fviige0btTbQf2hZQ6T8W?si=JkFKXt2fQSSrGSXfsaX0gg" target="_blank"
                    className={`${styles.musicBox} ${styles.drawing}`}></a>
            </div>
            <br />
        </>
    )
}

export default MusicWork
