// angular-portfolio-static/src/app/portfolio-animations/portfolio-animations.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-portfolio-animations',
  standalone: true,
  templateUrl: './portfolio-animations.component.html',
  styleUrls: ['./portfolio-animations.component.css']
})
export class PortfolioAnimationsComponent {
  videoSrc1: string = '/assets/videos/hna-hover.mp4';
  videoSrc2: string = '/assets/videos/bt-hover.mp4';

  onMouseEnter1() {
    this.videoSrc1 = '/assets/videos/hna.mp4';
  }

  onMouseLeave1() {
    this.videoSrc1 = '/assets/videos/hna-hover.mp4';
  }

  onMouseEnter2() {
    this.videoSrc2 = '/assets/videos/bt.mp4';
  }

  onMouseLeave2() {
    this.videoSrc2 = '/assets/videos/bt-hover.mp4';
  }
}

<h1 class="sectionTitle">Animated Videos</h1>

<div class="portfolioAnimation">

  <a href="https://www.youtube.com/watch?v=MUzcgtwxnr8" target="_blank">
    <div class="projectBox"
         (mouseenter)="onMouseEnter1()"
         (mouseleave)="onMouseLeave1()">
      <video class="bgVideo" [src]="videoSrc1" autoplay loop muted playsinline></video>
    </div>
  </a>

  <a href="https://www.youtube.com/watch?v=j1aYszgIKAs" target="_blank">
    <div class="projectBox"
         (mouseenter)="onMouseEnter2()"
         (mouseleave)="onMouseLeave2()">
      <video class="bgVideo" [src]="videoSrc2" autoplay loop muted playsinline></video>
    </div>
  </a>
</div>

// react-portfolio-static/src/components/PortfolioAnimations.jsx
import styles from "../styles/all.module.css";
import { useState } from "react";

function PortfolioAnimations() {
    const [videoSrc1, setVideoSrc1] = useState("/videos/hna-hover.mp4");
    const [videoSrc2, setVideoSrc2] = useState("/videos/bt-hover.mp4");
    return (
        <>
            <h1 className={styles.sectionTitle}>Animated Videos</h1>
            <div className={styles.portfolioAnimation}>
                <a href="https://www.youtube.com/watch?v=MUzcgtwxnr8" target="_blank">
                    <div className={styles.projectBox}
                        onMouseEnter={() => setVideoSrc1("/videos/hna.mp4")}
                        onMouseLeave={() => setVideoSrc1("/videos/hna-hover.mp4")}
                    >
                        <video className={styles.bgVideo} autoPlay loop muted playsInline src={videoSrc1}></video>
                    </div>
                </a>
                <a href="https://www.youtube.com/watch?v=j1aYszgIKAs" target="_blank">
                    <div className={styles.projectBox}
                        onMouseEnter={() => setVideoSrc2("/videos/bt.mp4")}
                        onMouseLeave={() => setVideoSrc2("/videos/bt-hover.mp4")}
                    >
                        <video className={styles.bgVideo} autoPlay loop muted playsInline src={videoSrc2}></video>
                    </div>
                </a>
            </div>
            <br /><br />
        </>
    )
}

export default PortfolioAnimations
