// angular-portfolio-static/src/app/portfolio-pages/portfolio-pages.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-portfolio-pages',
  imports: [],
  templateUrl: './portfolio-pages.component.html',
  styleUrl: './portfolio-pages.component.css'
})
export class PortfolioPagesComponent {

}

<h1 class="sectionTitle">Portfolio Pages</h1>

<div class="portfolioPages">
  <a href="https://eclipseplayer.com/" target="_blank">
    <div class="projectBox epImg">
      <h3 class="textOverlay">Eclipse Player</h3>
    </div>
  </a>

  <a href="https://icvacations.netlify.app/" target="_blank">
    <div class="projectBox icvImg">
      <h3 class="textOverlay">IceCream Vacations</h3>
    </div>
  </a>

  <a href="https://grandeplayer.netlify.app/player" target="_blank">
    <div class="projectBox gpImg">
      <h3 class="textOverlay">Grande Player</h3>
    </div>
  </a>

  <a href="https://cardwizard.up.railway.app/" target="_blank">
    <div class="projectBox cwImg">
      <h3 class="textOverlay">Card Wizard</h3>
    </div>
  </a>
</div>

// react-portfolio-static/src/components/PortfolioPages.jsx
import styles from "../styles/all.module.css";

function PortfolioPages() {
    return (
        <>
            <h1 className={styles.sectionTitle}>Portfolio Pages</h1>
            <div className={styles.portfolioPages}>
                <a href="https://eclipseplayer.com/" target="_blank">
                    <div className={`${styles.projectBox} ${styles.epImg}`}>
                        <h3 className={styles.textOverlay}>Eclipse Player</h3>
                    </div>
                </a>
                <a href="https://icvacations.netlify.app/" target="_blank">
                    <div className={`${styles.projectBox} ${styles.icvImg}`}>
                        <h3 className={styles.textOverlay}>IceCream Vacations</h3>
                    </div>
                </a>
                <a href="https://grandeplayer.netlify.app/player" target="_blank">
                    <div className={`${styles.projectBox} ${styles.gpImg}`}>
                        <h3 className={styles.textOverlay}>Grande Player</h3>
                    </div>
                </a>
                <a href="https://cardwizard.up.railway.app/" target="_blank">
                    <div className={`${styles.projectBox} ${styles.cwImg}`}>
                        <h3 className={styles.textOverlay}>Card Wizard</h3>
                    </div>
                </a>
            </div>
            <br /><br />
        </>
    )
}

export default PortfolioPages
